---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/statements":
    get:
      summary: list statements
      responses:
        '200':
          description: successful
    post:
      summary: create statement
      responses:
        '200':
          description: successful
  "/statements/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show statement
      responses:
        '200':
          description: successful
    patch:
      summary: update statement
      responses:
        '200':
          description: successful
    put:
      summary: update statement
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3001
